services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      # Mount source code for hot reload
      - ./frontend/next.config.mjs:/app/next.config.mjs
      - ./frontend/jsconfig.json:/app/jsconfig.json
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/tailwind.config.js:/app/tailwind.config.js
    networks:
      - scholarmind-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
      - vector_db
    environment:
      - DATABASE_URL=postgresql://scholarmind_user:scholarmind_pass@db:5432/scholarmind_db
      - VECTOR_DB_URL=http://vector_db:8000
      - PYTHONPATH=/app:/app/src
    volumes:
      # Mount source code for development
      - ./backend/src:/app/src
      - ./backend/tests:/app/tests
    networks:
      - scholarmind-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=scholarmind_db
      - POSTGRES_USER=scholarmind_user
      - POSTGRES_PASSWORD=scholarmind_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - scholarmind-network

  vector_db:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - scholarmind-network

volumes:
  postgres_data:
  chroma_data:

networks:
  scholarmind-network:
    driver: bridge
